css-two-column-layout exercise - Heerak Moon
hmoon2/c1222-code-solutions pull request #19
Opened 2022-12-12 11:20 UTC by hmoon2

![css-two-column-layout](https://user-images.githubusercontent.com/113075380/207032848-a02bc54b-1850-4a0b-9cfd-6bbacfb91961.JPG)

2022-12-12 23:52 UTC, codingcodymiller requested changes

2022-12-12 23:52 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      </div>
No column class? Why?

2022-12-12 23:52 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div>
No column class? Why?

2022-12-12 23:52 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div>
No column class? Why?

2022-12-12 23:52 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div>
No column class? Why?

2022-12-19 03:12 UTC, hmoon2 commented
![css-two-column-layout-changes](https://user-images.githubusercontent.com/113075380/208340240-b5c4b920-15f9-4e61-b194-ca5071b6fb64.JPG)

2022-12-19 17:38 UTC, codingcodymiller requested changes

2022-12-20 02:33 UTC, hmoon2 commented
![css-two-column-layout-resubmit](https://user-images.githubusercontent.com/113075380/208568386-22303f1d-fe9d-4451-8bee-9f3b15122768.png)

2022-12-27 17:09 UTC, codingcodymiller approved these changes

2022-12-27 23:07 UTC, merged