css-three-column-layout exercise - Heerak Moon
hmoon2/c1222-code-solutions pull request #20
Opened 2022-12-12 11:38 UTC by hmoon2

![css-three-column-layout](https://user-images.githubusercontent.com/113075380/207035960-2d9374f3-9c51-40c9-9245-c2b38fc48dfb.JPG)

2022-12-12 19:35 UTC, codingcodymiller requested changes

2022-12-12 19:35 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  margin-bottom: 30px;
`column` classes should only have `flex-basis` applied, nothing else.

2022-12-12 19:35 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  padding: 0 25px;
`column` classes should only have `flex-basis` applied, nothing else.

2022-12-12 19:35 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
this should be your `container` class, but with `max-width` rather than `width`. You should likely review the layout classes exercise again, having a deep understanding of the mechanics of layout classes will be essential going forward.

2022-12-19 01:33 UTC, hmoon2 commented
![css-three-column-layout-changes](https://user-images.githubusercontent.com/113075380/208331247-51442523-0b31-477a-ae14-6b0ce7197c4c.JPG)

2022-12-19 17:34 UTC, codingcodymiller requested changes

2022-12-19 17:34 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  margin: auto;
`margin: auto` should be on the `container` class

2022-12-27 17:09 UTC, codingcodymiller approved these changes

2022-12-27 23:07 UTC, merged