Css-four-column-layout exercise - Heerak Moon
hmoon2/c1222-code-solutions pull request #36
Opened 2022-12-19 08:20 UTC by hmoon2

![css-four-column-layout](https://user-images.githubusercontent.com/113075380/208379544-6b365796-1303-4ac9-920b-3c4541b19d0a.JPG)

2022-12-19 17:41 UTC, codingcodymiller requested changes

2022-12-19 17:41 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +    </div>
I can understand why you would separate this into three rows based on setting it up with layout classes, but now your HTML makes it seem like the images, headers, and subtext are not related, and they absolutely are. You should instead have the images, header, and subtext together inside one `col-fourth`

2022-12-26 09:01 UTC, hmoon2 commented
![css-four-column-layout-edit](https://user-images.githubusercontent.com/113075380/209528850-bbe7b243-36bd-4c08-80f2-395c2fa5522f.JPG)

2022-12-27 17:17 UTC, codingcodymiller approved these changes

2022-12-27 23:06 UTC, merged