Css-ecommerce-page -
hmoon2/c1222-code-solutions pull request #37
Opened 2022-12-19 09:50 UTC by hmoon2

2022-12-19 09:51 UTC, hmoon2 commented
![css-ecommerce-page](https://user-images.githubusercontent.com/113075380/208397528-84c088ef-b5fc-44ca-8330-9b1ade1969c0.JPG)

2022-12-19 17:54 UTC, codingcodymiller requested changes

2022-12-19 17:54 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +</body>
I can understand why you would do this from a layout class perspective, but these images are related to the text below them, and dividing your page like this makes them seem unrelated when reading the HTML document. I suggest you keep the images and text together inside one `col-fifth`

2022-12-26 09:26 UTC, hmoon2 commented
![css-ecommerce-page-changes](https://user-images.githubusercontent.com/113075380/209531673-3974d2c8-8094-4f11-9f1c-68e4d26876be.JPG)

2022-12-27 17:20 UTC, codingcodymiller approved these changes

2022-12-27 23:06 UTC, merged