html-forms exercise - Heerak Moon
hmoon2/c1222-code-solutions pull request #7
Opened 2022-12-06 20:25 UTC by hmoon2

https://user-images.githubusercontent.com/113075380/206015351-3292e533-e2aa-4926-a3c7-502752c21eeb.mp4

2022-12-06 22:05 UTC, codingcodymiller requested changes

2022-12-06 22:05 UTC, codingcodymiller commented on html-forms/index.html
> +        <input type="text" name="email">
This needs an `id` that matches the `for` on its `label` to be properly configured.

2022-12-06 22:05 UTC, codingcodymiller commented on html-forms/index.html
> +        <select name="options">
This needs an `id` that matches the `for` on its `label` to be properly configured.

2022-12-06 22:05 UTC, codingcodymiller commented on html-forms/index.html
> +        <textarea rows="10" cols="35"></textarea>
This needs an `id` that matches the `for` on its `label` to be properly configured.

2022-12-09 10:40 UTC, hmoon2 commented
![html-forms-fix](https://user-images.githubusercontent.com/113075380/206684079-6fc2a117-1c11-416b-ae00-82b0f147a863.png)

2022-12-09 18:27 UTC, codingcodymiller approved these changes

2022-12-09 22:59 UTC, merged