html-web-page challenge - Heerak Moon
hmoon2/c1222-code-solutions pull request #9
Opened 2022-12-06 22:44 UTC by hmoon2

![html-web-page](https://user-images.githubusercontent.com/113075380/206039981-e09ae996-9c2d-4a84-b587-fad48d14712a.png)

2022-12-06 22:49 UTC, codingcodymiller requested changes

2022-12-06 22:49 UTC, codingcodymiller commented on html-web-page/index.html
> +  <input type="submit" value="Submit">
These should be in a `form`

2022-12-09 10:54 UTC, hmoon2 commented
![html-web-page-fix](https://user-images.githubusercontent.com/113075380/206686681-a4d27ec2-058c-4748-bb21-887b45fe5928.png)

2022-12-09 18:27 UTC, codingcodymiller approved these changes

2022-12-09 22:59 UTC, merged